export type Project = {
  id: string;
  title: string;
  description: string;
  tech: readonly string[];
  link: string;
  /** Footer category this project lives in ('extension' has no entries yet) */
  kind: 'website' | 'tool' | 'extension';
  /** Featured projects get the big card treatment on the homepage */
  featured?: boolean;
  /** Only linked from the footer, not shown in the projects section */
  footerOnly?: boolean;
  /** One concrete proof point, shown on featured cards */
  proof?: string;
};

export const projects: readonly Project[] = [
  {
    id: '01',
    title: 'VizLearn',
    description:
      'A bite-sized learning site for algorithms and data structures, with visual lessons on arrays, linked lists, trees, graphs, hash tables, and heaps.',
    tech: ['Algorithms', 'Data Structures'],
    link: 'https://vizlearn.app/',
    kind: 'website',
    featured: true,
    proof: 'Designed and built solo — six topic tracks, every lesson visual.',
  },
  {
    id: '02',
    title: 'AouoAI',
    description:
      "A playful AI usage dashboard styled like Anya's field notebook, tracking token spend, replies, model activity, and budget with chart-driven views.",
    tech: ['AI Dashboard', 'Chart.js'],
    link: 'https://aouoai.com/',
    kind: 'tool',
    featured: true,
    proof: 'Every chart is fed by my own day-to-day AI usage.',
  },
  {
    id: '03',
    title: 'AOUI',
    description:
      'A design token reference for the AOUI system, documenting colors, spacing, radii, typography, and motion for consistent product interfaces.',
    tech: ['Design Tokens', 'UI System'],
    link: 'https://aoui.aouos.com/',
    kind: 'tool',
    footerOnly: true,
  },
  {
    id: '04',
    title: 'AOUOS LOGO',
    description:
      'A dedicated brand asset page for downloading the AOUOS logo in SVG plus transparent and white-background PNG exports in multiple sizes.',
    tech: ['SVG', 'Brand Assets'],
    link: 'https://logo.aouos.com/',
    kind: 'tool',
    footerOnly: true,
  },
  {
    id: '05',
    title: 'Watermark Remover',
    description:
      'A local tool for removing watermarks from images generated by nano banana. Built with Vue.js for high performance.',
    tech: ['Vue.js', 'Canvas API'],
    link: 'https://wmremover.aouos.com/',
    kind: 'tool',
  },
  {
    id: '06',
    title: 'React 19 Learning',
    description:
      'A project-driven learning system for React 19, covering 30 lessons from core fundamentals to source-code mastery across 4 progressive phases.',
    tech: ['React 19', 'VitePress'],
    link: 'https://react.aouos.com',
    kind: 'website',
  },
  {
    id: '07',
    title: 'Vue 3 Learning',
    description:
      'A project-driven learning system for Vue 3, covering 4 phases from a Todo App to full-stack e-commerce and Vue 3 internals, with deep dives into Composition API throughout.',
    tech: ['Vue 3', 'VitePress'],
    link: 'https://vue.aouos.com',
    kind: 'website',
  },
] as const;

/** Social accounts — same handle everywhere. */
export const socials = [
  { name: 'GitHub', icon: 'github', href: 'https://github.com/boltguo' },
  { name: 'X', icon: 'x', href: 'https://x.com/boltguo' },
  { name: 'YouTube', icon: 'youtube', href: 'https://youtube.com/@boltguo' },
  {
    name: 'Instagram',
    icon: 'instagram',
    href: 'https://instagram.com/boltguo',
  },
  {
    name: 'Bilibili',
    icon: 'bilibili',
    href: 'https://space.bilibili.com/48999569',
  },
] as const;
